### PR TITLE
Roku receipt validation

### PR DESCRIPTION
**Pull request by gastonelhordoy**

### CODE REVIEW

**Comment by gastonelhordoy** [comment]
Hey @voltrue2, this is a first version of integration with Roku. I still have to look into how to implement tests, but in the meantime let me know if you have any feedback.

Cheers

**Comment by voltrue2** [comment]
Hello and thank you for the PR!

It looks like your commits fail the tests. Would you mind looking at those first?

Cheers

**Comment by gastonelhordoy** [comment]
Hey @voltrue2, is there any chance that test could be randomly failing?

If you check [Travis execution #186](https://travis-ci.org/voltrue2/in-app-purchase/builds/272946249) and [execution #187](https://travis-ci.org/voltrue2/in-app-purchase/builds/272954671) they failed for different reasons and in code that was not modified in any way. Furthermore, commit 3820add0431da2d07d1247a8b888e0187deccde5 that triggered execution 187 didn't change any of files that were causing failures in 186.

**Comment by gastonelhordoy** [comment]
Ya... I think there might be something broken inside tests, I pushed an empty commit 5125858d34830d28545c017fd83a198f67dc1c66 with no changes at all in code and now Travis reported success.
Anyways, what do you think about it so far? Any comment/feedback? I don't know how to create a test without publishing sensible data.

**Comment by voltrue2** [comment]
@gastonelhordoy 

I see. Sorry about that. I will look into the tests after I look at your PR! 

Cheers!

**Comment by voltrue2** [comment]
Merged!

Thank you for the PR!

**Comment by gastonelhordoy** [comment]
That's excellent news @voltrue2 , thank you very much!

**Pull request merged**
