### PR TITLE
added new pending renewal info fields to last purchase data entry

### PR DESCRIPTION
**Pull request by gpinkham**

### CODE REVIEW

**Comment by voltrue2** [comment]
Hello 
Thanks for the PR. It seems the change has broken the CI tests.
Would you have a look at it and correct it?

Cheers

**Comment by gpinkham** [comment]
sorry about that..   Didn't realize `let` wouldn't work in the older nodejs builds..      all fixed now..  

best...
Gary

**Comment by voltrue2** [comment]
Hello
Thanks for the update to the PR.
I have one last comment on it. If you don't mind handling it, it would be awesome.
Thanks again.
Cheers

**Comment by gpinkham** [comment]
@voltrue2    sure..  whatever needs changing I'll do.. let me know and I'll get on it today..  

thanks
Gary

**Comment by gpinkham** [comment]
I had forgotten that pushing to my develop branch would add to the PR I had open with you..     I switched up where the google purchaseState was coming from..       one of the builds failed simply for a timeout..  probably just needs to be retried but I don't have access to hit the restart button in travis..       Let me know what you wanted changed..    thanks!

**Pull request closed without merging**
