### PR TITLE
Include the application's "bundle_id"

### PR DESCRIPTION
**Pull request by ember-max**
Allows an application to either share a server for multiple SKUs, or just to perform extra validation.

### CODE REVIEW

**Comment by ember-max** [comment]
See Apple's documentation: https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW1

**Comment by voltrue2** [comment]
Hello

Thank you for the PR! Would you mind updating the `.getPurchase()` section of README also?

**Comment by ember-max** [comment]
Added, thanks for quick reply!

**Comment by voltrue2** [comment]
Merged! Thank you for the PR

**Pull request merged**
