### PR TITLE
Updated request module to latest version to prevent `in-app-purchase …

### PR DESCRIPTION
**Pull request by markoshust**
…> request > node-uuid@1.4.7: use uuid module instead` deprecation notice

### CODE REVIEW

**Comment by voltrue2** [comment]
Hello,

Thanks for the PR, but would you fix the try fix the unit test breaks?

Cheers

**Comment by markoshust** [comment]
What are the unit test breaks? All that's included in here is bumping a package version.

**Comment by voltrue2** [comment]
I understand the change is just to update the dependency version update, but my Travis CI is failing

**Comment by markoshust** [comment]
Where can I view the build failing? I will check it out but don't see a failed build flag (but I'm on mobile, perhaps that's why).

**Comment by voltrue2** [comment]
This is the link: https://travis-ci.org/voltrue2/in-app-purchase/builds/196390017

I am not sure if you can see it though. Please let me know if you cannot see it. I can get you the details in that case.

Cheers!

**Comment by markoshust** [comment]
Thank you -- I see it. It looks like a generic Linux/npm  error. Can we try re-running the build test again?

**Comment by markoshust** [comment]
Here's a screenshot of what I'm seeing. It looks like a core/build problem? 
screen shot 2017-02-27 at 10 13 27 am

**Comment by markoshust** [comment]
Ah - `request` package version `2.79.1` was published to github but never to npm. I reverted it down to version `2.79.0` - this should pass the build just fine.

**Comment by voltrue2** [comment]
Merged! Thank you!

**Pull request merged**
