### PR TITLE
Add Promise support

### PR DESCRIPTION
**Pull request by superandrew213**
Added promise support. Let me know if I missed something or if you want me to change anything.

### CODE REVIEW

**Comment by voltrue2** [comment]
Hello

Thank you for this PR.
I will go over the code as soon as I get the chance!

Cheers

**Comment by voltrue2** [comment]
Merged! Thank you!!!

**Comment by superandrew213** [comment]
Awesome!! Thanks!

Quick question: Is there a better way to handle error messages for promises. It works fine with callbacks since you can also pass back a data object with error status and message, like here:
https://github.com/voltrue2/in-app-purchase/blob/develop/lib/apple.js#L294

However with promises you only get back error object which in this case will just be `failed to validate purchase`.

**Comment by voltrue2** [comment]
Hello,

Yeah that is a tough one as Promise error handling gives you no room for custom behaviour as you have mentioned in https://github.com/voltrue2/in-app-purchase/blob/develop/lib/apple.js#L294.

I think the simplest way to solve this is to include the stringified `data` in the error message...

**Comment by superandrew213** [comment]
Sounds good to me. Can you give me an example of you want to include the stringified `data` object in the error message? Just use it instead of the current error message?

**Comment by superandrew213** [comment]
`validate`, `validateOnce` and `refreshGoogleToken` all return a data object `{ status: 123, message: 'error message' }` if an error occurs. We could just stringify this and pass it as the error message.

`setup` doesn't return a data object. We can just pass this `{ status: null, message: error }` so that it is always consistent.

What do you think?

**Pull request merged**
