### PR TITLE
Update request library for security

### PR DESCRIPTION
**Pull request by dankang**
* request version: 2.69.0 => 2.75.0
* please check this: https://nodesecurity.io/check/in-app-purchase

### CODE REVIEW

**Comment by voltrue2** [comment]
Merged! Thank you for the PR!

Really appreciate your help.

**Comment by dankang** [comment]
Thank you for this great library!

**Comment by voltrue2** [comment]
I will be publishing the updated version of the library on npm as soon as I finish testing!

**Comment by dankang** [comment]
Perfect!
Thanks a lot!

**Pull request merged**
