### PR TITLE
Improve promise errors

### PR DESCRIPTION
**Pull request by superandrew213**
@voltrue2 what do you think about this?

### CODE REVIEW

**Comment by voltrue2** [comment]
Hello
Thanks for the PR, but JSON.stringify without try/catch would be a dangerous move because it could throw an exception.
Also the change seems to cause the CI tests.
Cheers

**Comment by voltrue2** [comment]
Thank you!

**Comment by voltrue2** [comment]
Merged!

**Comment by superandrew213** [comment]
Oh I wasn't finished :). I will improve the code a little. Extract the promise callback handle into its own function since it is repeated 3 times. And also always return JSON.stringify({ status: null, message: error })) if there is an error with no response.

The code will work fine how it is now, but I will create a new PR to make the other changes.

**Comment by voltrue2** [comment]
Sure no worries

**Pull request merged**
