### PR TITLE
FIX: receipt.data should be stringified instead of receipt.

### PR DESCRIPTION
**Pull request by cemuzunlar**

### CODE REVIEW

**Comment by voltrue2** [comment]
Hello,

Thank you for the PR! Travis CI tests seem to have failed. Would you mind having a look at it?

Cheers!

**Comment by cemuzunlar** [comment]
It is an Apple sandbox timeout which happens a lot. Nothing related to the fix.

**Comment by voltrue2** [comment]
Oh I see. Yeah it happens here and there.
Thanks for checking it.
I’ll get to your PR ASAP!

Cheers!

**Comment by voltrue2** [comment]
Merged! Thank you!

**Pull request merged**
